### ISSUE TITLE
Add option to show commands that don't *yet* have a shortcut

### ISSUE THREAD

**Issue by jcansdale** [madskristensen/ShowTheShortcut#6]
### Problem
There are some commands that I use and would add a shortcut for if I knew what they were!

### Feature request
Have option to show commands on 'Learn the Shortcut' pane that don't have an associated shortcut.
Having a count of how many times the command was used might also be interesting.

---
Thanks for all of your excellent extensions! 😄

**Comment by jakubsuchybio** [comment]
Ad Twitter conversation:
This is exactly what I ment.
If I have some action lets say right click project-> Debug -> Start New Instance:
![](http://i.imgur.com/kA4rR28.png)
This action doesn't have shortcut by default and I wanted to set it, but I am stupid and I could find it in Tools->Options->Environment->Keyboard for hours. So I gave up. 

But then I wanted to replicate this behaviour with Macros Extension, because I was using this so much and it was so cumbersome to clicking it by hand.

After recording a macro I found the command name in macro file and I was then able to find and filter it in Keyboard to be able to set shortcut for it.

But I think it would be awesome to log into "Learn the Shortcut" output window all user actions as commands and not just the ones with the shortcut.

**Comment by madskristensen** [comment]
I like the idea. It would be a simple add. Should it always log the command names executed or should users opt in to that from Tools -> Options?

**Comment by jakubsuchybio** [comment]
I think it would be better if it would show the executed commands by default. Then it would be easier to find for users that wouldn't know about this functionality.

**Comment by madskristensen** [comment]
Also, should it log the command name, guid and id or just the name?

Example: `Tools.DiffFiles (GUID: <guid>, ID: 1234)`

**Comment by madskristensen** [comment]
I guess for keyboard bindings you don't care about guids and ids

**Comment by jakubsuchybio** [comment]
Hmm. For the sake of this functionality, the command name would be enough. Because that is the exact name to search for in Keyboard to assign shortcut.
I don't know if user would need guid or id of the command. Those are used only for using commands when creating extensions no?
